const menu = [
	{
		id: 1,
		title: "strawberries",
		category: "breakfast",
		price: 9.5,
		image:
			"bowl-strawberries-knife-wooden-cutting-board-dark-blue-marble-white-wooden-board-background-close-up-free-space-your-text_176474-29876.jpeg",
		description: "",
	},
	{
		id: 2,
		title: "cooked egg",
		category: "breakfast",
		price: 9.5,
		image: "breakfast-cooked-egg-vintage-top_1203-3815.jpeg",
		description: "",
	},
	{
		id: 3,
		title: "eggs buns with cheese",
		category: "breakfast",
		price: 9.5,
		image:
			"front-view-breakfast-table-with-eggs-buns-cheese-fresh-juice-restaurant-during-daytime-food-meal-breakfast_140725-25904.jpeg",
		description: "",
	},
	{
		id: 4,
		title: "breakfast with coffee croissants",
		category: "breakfast",
		price: 9.5,
		image: "healthy-breakfast-with-coffee-croissants_80013-4275.jpeg",
		description: "",
	},
	{
		id: 5,
		title: "homemade smoothie bowl made with berries",
		category: "breakfast",
		price: 9.5,
		image: "homemade-smoothie-bowl-made-with-berries_1220-4560.jpeg",
		description: "",
	},
	{
		id: 6,
		title: "juice coffee and buns",
		category: "breakfast",
		price: 9.5,
		image: "juice-coffee-near-buns_23-2147798969.jpeg",
		description: "",
	},
	{
		id: 7,
		title: "fried eggs salmon broccoli",
		category: "breakfast",
		price: 9.5,
		image:
			"ketogenic-paleo-diet-fried-eggs-salmon-broccoli-microgreen-keto-breakfast-brunch_2829-20252.jpeg",
		description: "",
	},
	{
		id: 8,
		title: "pancake with fresh blueberries",
		category: "breakfast",
		price: 9.5,
		image:
			"pancake-with-fresh-blueberries-fresh-strawberries-honey_1339-53929.jpeg",
		description: "",
	},
	{
		id: 9,
		title: "sandwich",
		category: "breakfast",
		price: 9.5,
		image: "sandwich_1339-1114.jpeg",
		description: "",
	},
	{
		id: 10,
		title: "sandwich with egg served with lettuce",
		category: "breakfast",
		price: 9.5,
		image: "sandwich-with-egg-served-with-lettuce_140725-8045.jpeg",
		description: "",
	},
	{
		id: 11,
		title: "scrambled eggs meat with fried potatoes toast",
		category: "breakfast",
		price: 9.5,
		image: "scrambled-eggs-meat-with-fried-potatoes-toast_155003-11528.jpeg",
		description: "",
	},
	{
		id: 12,
		title: "fried curry paste with bamboo shoot with minced pork",
		category: "breakfast",
		price: 9.5,
		image:
			"stir-fried-curry-paste-with-bamboo-shoot-minced-pork_1150-35171.jpeg",
		description: "",
	},
	{
		id: 13,
		title: "oatmeal porridge with berry flax seeds nuts",
		category: "breakfast",
		price: 9.5,
		image:
			"tasty-healthy-oatmeal-porridge-with-berry-flax-seeds-nuts-healthy-breakfast-fitness-food-proper-nutrition_2829-11260.jpeg",
		description: "",
	},
	{
		id: 14,
		title: "toast egg bacon tomatoes and microgreens salad",
		category: "breakfast",
		price: 9.5,
		image: "toast-egg-bacon-tomatoes-microgreens-salad_2829-4805.jpeg",
		description: "",
	},
	{
		id: 15,
		title: "scrambled eggs with sliced sausages and fresh tomatoes",
		category: "breakfast",
		price: 9.5,
		image:
			"top-view-scrambled-eggs-with-sliced-sausages-fresh-tomatoes-raw-eggs-dark-background_140725-58191.jpeg",
		description: "",
	},
];

const menu2 = [
	{
		id: 1,
		title: "pasta with tomato sauce bolognese",
		category: "lunch",
		price: 9.5,
		image:
			"asty-colorful-appetizing-cooked-spaghetti-italian-pasta-with-tomato-sauce-bolognese_117406-131.jpeg",
		description: "",
	},
	{
		id: 2,
		title: "baked salmon garnished with asparagus tomatoes with herbs",
		category: "lunch",
		price: 9.5,
		image:
			"baked-salmon-garnished-with-asparagus-tomatoes-with-herbs_2829-14516.jpeg",
		description: "",
	},
	{
		id: 3,
		title: "chicken rice bento",
		category: "lunch",
		price: 9.5,
		image: "chicken-rice-bento_1387-767.jpeg",
		description: "",
	},
	{
		id: 4,
		title: "chicken steak with lemon tomato chili and carrot",
		category: "lunch",
		price: 9.5,
		image:
			"chicken-steak-with-lemon-tomato-chili-carrot-white-plate_1150-25888.jpeg",
		description: "",
	},
	{
		id: 5,
		title: "fish steak",
		category: "lunch",
		price: 9.5,
		image: "fish-steak_1339-930.jpeg",
		description: "",
	},
	{
		id: 6,
		title: "meal assortment",
		category: "lunch",
		price: 9.5,
		image: "flat-lay-local-food-meal-assortment_23-2148833768.jpeg",
		description: "",
	},
	{
		id: 7,
		title: "fried pork",
		category: "lunch",
		price: 9.5,
		image: "fried-pork_100342-111.jpeg",
		description: "",
	},
	{
		id: 8,
		title: "griled chicken breast steak with vegetable",
		category: "lunch",
		price: 9.5,
		image: "griled-chicken-breast-steak-with-vegetable_1339-74114.jpeg",
		description: "",
	},
	{
		id: 9,
		title: "grilled steak with potato wedges",
		category: "lunch",
		price: 9.5,
		image: "grilled-steak-with-potato-wedges_93675-39134.jpeg",
		description: "",
	},
	{
		id: 10,
		title: "chicken bulgur microgreens tomato fruit",
		category: "lunch",
		price: 9.5,
		image:
			"lunch-box-chicken-bulgur-microgreens-tomato-fruit-healthy-fitness-food-take-away-lunchbox-top-view_2829-19657.jpeg",
		description: "",
	},
	{
		id: 11,
		title: "lunch box",
		category: "lunch",
		price: 9.5,
		image:
			"man-eating-lunch-from-takeaway-lunch-box-working-table_98936-6.jpeg",
		description: "",
	},
	{
		id: 12,
		title: "penne pasta with meatballs and tomato sauce",
		category: "lunch",
		price: 9.5,
		image: "penne-pasta-with-meatballs-tomato-sauce-white-bowl_2829-7663.jpeg",
		description: "",
	},
	{
		id: 13,
		title: "rice pork fried with holy basil white thai",
		category: "lunch",
		price: 9.5,
		image:
			"rice-pork-fried-with-holy-basil-white-thai-style-food_55716-3050.jpeg",
		description: "",
	},
	{
		id: 14,
		title: "kung river prawn spicy soup",
		category: "lunch",
		price: 9.5,
		image: "thai-food-tom-yum-kung-river-prawn-spicy-soup_1150-35465.jpeg",
		description: "",
	},
	{
		id: 15,
		title: "roasted chicken salad",
		category: "lunch",
		price: 9.5,
		image: "utensils-near-roasted-chicken-salad_23-2147765358.jpeg",
		description: "",
	},
];

const menu3 = [
	{
		id: 1,
		title: "barley soup with carrots tomato celery and meat",
		category: "dinner",
		price: 9.5,
		image:
			"barley-soup-with-carrots-tomato-celery-meat-dark-background-top-view_2829-5602.jpeg",
		description: "",
	},
	{
		id: 2,
		title: "chicken steak with lemon tomato chili carrot",
		category: "dinner",
		price: 9.5,
		image:
			"chicken-steak-with-lemon-tomato-chili-carrot-white-plate_1150-25888.jpeg",
		description: "",
	},
	{
		id: 3,
		title: "medium rare cooked steaks prawns sauce and grilled chicken leg",
		category: "dinner",
		price: 9.5,
		image:
			"dinner-setup-with-medium-rare-cooked-steaks-prawns-sauce-grilled-chicken-leg_141793-2232.jpeg",
		description: "",
	},
	{
		id: 4,
		title: "roasted ham",
		category: "dinner",
		price: 9.5,
		image:
			"festive-holiday-dinner-with-roasted-christmas-ham-food-photography_53876-95452.jpeg",
		description: "",
	},
	{
		id: 5,
		title: "salad with different ingredients",
		category: "dinner",
		price: 9.5,
		image: "flat-lay-salad-with-different-ingredients_23-2148537172.jpeg",
		description: "",
	},
	{
		id: 6,
		title: "sandwich made meat grilled spit with sour cream",
		category: "dinner",
		price: 9.5,
		image:
			"front-close-view-delicious-meat-sandwich-made-meat-grilled-spit-with-sour-cream-blue-desk_140725-61511.jpeg",
		description: "",
	},
	{
		id: 7,
		title: "rotini pasta with chopped greens bowl cherry tomatoes",
		category: "dinner",
		price: 9.5,
		image:
			"front-view-rotini-pasta-plate-fork-female-hand-chopped-greens-bowl-cherry-tomatoes-grey-surface_140725-62566.jpeg",
		description: "",
	},
	{
		id: 8,
		title: "penne pasta with meatballs tomato sauce",
		category: "dinner",
		price: 9.5,
		image: "penne-pasta-with-meatballs-tomato-sauce-white-bowl_2829-7663.jpeg",
		description: "",
	},
	{
		id: 9,
		title: "pork green curry brown bowl with spices",
		category: "dinner",
		price: 9.5,
		image:
			"pork-green-curry-brown-bowl-with-spices-black-cement-background_1150-35201.jpeg",
		description: "",
	},
	{
		id: 10,
		title: "pork-green-curry-white-bowl-with-spices",
		category: "dinner",
		price: 9.5,
		image:
			"pork-green-curry-white-bowl-with-spices-black-cement-background_1150-35197.jpeg",
		description: "",
	},
	{
		id: 11,
		title: "raw pasta rustic",
		category: "dinner",
		price: 9.5,
		image: "raw-pasta-rustic-wooden-cup-grey-marble_114579-33548.jpeg",
		description: "",
	},
	{
		id: 12,
		title: "fried curry paste with bamboo whit shoot minced pork",
		category: "dinner",
		price: 9.5,
		image:
			"stir-fried-curry-paste-with-bamboo-shoot-minced-pork_1150-35178.jpeg",
		description: "",
	},
	{
		id: 13,
		title: "fried zucchini with minced pork",
		category: "dinner",
		price: 9.5,
		image: "stir-fried-zucchini-with-minced-pork-white-plate_1150-35183.jpeg",
		description: "",
	},
	{
		id: 14,
		title: "recipe idea",
		category: "dinner",
		price: 9.5,
		image: "table-two-food-photography-recipe-idea_53876-47154.jpeg",
		description: "",
	},
	{
		id: 15,
		title: "cooked sliced potatoes with greens",
		category: "dinner",
		price: 9.5,
		image:
			"top-close-view-cooked-sliced-potatoes-with-greens-inside-brown-plate-dark-blue-surface_140725-61759.jpeg",
		description: "",
	},
];

const menu4 = [
	{
		id: 1,
		title: "cocktail with lemon slices ice cubes mint",
		category: "drinks",
		price: 9.5,
		image: "cocktail-with-lemon-slices-ice-cubes-mint_141793-581.jpeg",
		description: "",
	},
	{
		id: 2,
		title: "cocolate cocoa blend with cake coffee",
		category: "drinks",
		price: 9.5,
		image: "cocolate-cocoa-blend-with-cake-coffee-shop_1150-10443.jpeg",
		description: "",
	},
	{
		id: 3,
		title: "delicious beverage with lime ice",
		category: "drinks",
		price: 9.5,
		image: "delicious-beverage-with-lime-ice_23-2148751853.jpeg",
		description: "",
	},
	{
		id: 4,
		title: "fresh cola drink with green lime",
		category: "drinks",
		price: 9.5,
		image: "fresh-cola-drink-with-green-lime_144627-12396.jpeg",
		description: "",
	},
	{
		id: 5,
		title: "fresh lime drinks macro shot",
		category: "drinks",
		price: 9.5,
		image: "fresh-lime-drinks-macro-shot_53876-42483.jpeg",
		description: "",
	},
	{
		id: 6,
		title: "glass cola with ice",
		category: "drinks",
		price: 9.5,
		image: "glass-cola-with-ice_1339-2536.jpeg",
		description: "",
	},
	{
		id: 7,
		title: "orange lemonade drink",
		category: "drinks",
		price: 9.5,
		image: "glass-with-orange-lemonade-drink_23-2148606459.jpeg",
		description: "",
	},
	{
		id: 8,
		title: "iced cocktail",
		category: "drinks",
		price: 9.5,
		image: "iced-cocktails-drinking-glass_1203-9532.jpeg",
		description: "",
	},
	{
		id: 9,
		title: "iced cocktails",
		category: "drinks",
		price: 9.5,
		image: "iced-cocktails-drinking-glass-with-beach-sea_74190-7650.jpeg",
		description: "",
	},
	{
		id: 10,
		title: "juice fresh passion fruit",
		category: "drinks",
		price: 9.5,
		image:
			"jar-passion-fruit-juice-fresh-passion-fruit-cut-half-place-dark-floor_1150-35258.jpeg",
		description: "",
	},
	{
		id: 11,
		title: "red cocktail with lemon orange",
		category: "drinks",
		price: 9.5,
		image:
			"red-cocktail-with-lemon-orange-slices-hreen-herbs-by-pool_114579-3582.jpeg",
		description: "",
	},
	{
		id: 12,
		title: "red fresh cocktail with ice lime",
		category: "drinks",
		price: 9.5,
		image: "red-fresh-cocktail-with-ice-lime_221774-506.jpeg",
		description: "",
	},
	{
		id: 13,
		title: "rosemary hot tea",
		category: "drinks",
		price: 9.5,
		image: "rosemary-hot-tea-cup-ready-drink_1150-35587.jpeg",
		description: "",
	},
	{
		id: 14,
		title: "rosemary hot tea cup ready drink",
		category: "drinks",
		price: 9.5,
		image: "rosemary-hot-tea-cup-ready-drink_1150-35603.jpeg",
		description: "",
	},
	{
		id: 15,
		title: "tea cinnamon saucer with flower ribbon",
		category: "drinks",
		price: 9.5,
		image:
			"side-view-cup-tea-cinnamon-saucer-with-flower-ribbon-blue-background_141793-49476.jpeg",
		description: "",
	},
];
